services:
  eureka-service:
    build:
      context: ./ESportWebApp_EurekaDiscovery
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8080"

  player-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: player_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  organization-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: organization_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  player-service-1:
    build:
      context: ./ESportWebApp_Player
      dockerfile: Dockerfile
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://player-db:5432/player_db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
    depends_on:
      - eureka-service
      - player-db

  player-service-2:
    build:
      context: ./ESportWebApp_Player
      dockerfile: Dockerfile
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "2"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://player-db:5432/player_db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
    depends_on:
      - eureka-service
      - player-db

  organization-service-1:
    build:
      context: ./ESportWebApp_Organization
      dockerfile: Dockerfile
    restart: always
    environment:
      PLAYER_SERVICE_APPNAME: "esport-players-service"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://organization-db:5432/organization_db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
    depends_on:
      - eureka-service
      - organization-db


  organization-service-2:
    build:
      context: ./ESportWebApp_Organization
      dockerfile: Dockerfile
    restart: always
    environment:
      PLAYER_SERVICE_APPNAME: "esport-players-service"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "2"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://organization-db:5432/organization_db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
    depends_on:
      - eureka-service
      - organization-db


  gateway:
    build:
      context: ./ESportWebApp_Gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    environment:
      GATEWAY_HOST: "gateway:8080"
      PLAYER_SERVICE_APPNAME: esport-players-service
      ORGANIZATION_SERVICE_APPNAME: esport-organizations-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
    depends_on:
      - eureka-service
      - player-service-1
      - player-service-2
      - organization-service-1
      - organization-service-2
      
  frontend-ng:
    build: 
      context: ./angular-frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      API_URL: http://gateway:8080/api
    ports:
      - "8085:80"
